<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #1a1a2e; }

  .page-break { page-break-after: always; }

  /* ── Cover page ── */
  .cover { background: #087f83; color: #fff; min-height: 100vh; padding: 60px 50px; }
  .cover h1 { font-size: 28px; font-weight: bold; margin-bottom: 8px; }
  .cover .subtitle { font-size: 14px; opacity: 0.85; margin-bottom: 50px; }
  .cover .org { font-size: 20px; font-weight: bold; margin-bottom: 6px; }
  .cover .generated { font-size: 10px; opacity: 0.7; margin-top: 40px; }
  .cover table { width: 100%; border-collapse: collapse; margin-top: 30px; }
  .cover table td { padding: 8px 0; border-bottom: 1px solid rgba(255,255,255,0.2); color: #fff; }
  .cover table td:first-child { opacity: 0.75; width: 40%; }

  /* ── Body pages ── */
  .page { padding: 40px 50px; }
  h2 { font-size: 16px; font-weight: bold; color: #087f83; border-bottom: 2px solid #087f83; padding-bottom: 6px; margin-bottom: 16px; }
  h3 { font-size: 12px; font-weight: bold; color: #333; margin: 16px 0 8px; }

  /* ── Stat cards (inline) ── */
  .stat-row { display: table; width: 100%; margin-bottom: 16px; }
  .stat-cell { display: table-cell; width: 25%; padding: 10px 8px; text-align: center; background: #f0fdfe; border: 1px solid #b2e8ea; border-radius: 6px; }
  .stat-cell + .stat-cell { margin-left: 4px; }
  .stat-number { font-size: 22px; font-weight: bold; color: #087f83; }
  .stat-label { font-size: 9px; color: #555; margin-top: 3px; }

  /* ── Tables ── */
  table.data { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  table.data th { background: #087f83; color: #fff; padding: 6px 8px; text-align: left; font-size: 9px; }
  table.data td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; font-size: 9px; vertical-align: top; }
  table.data tr:nth-child(even) td { background: #f8fffe; }

  /* ── Badges ── */
  .badge { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 8px; font-weight: bold; }
  .badge-green { background: #d1fae5; color: #065f46; }
  .badge-red { background: #fee2e2; color: #991b1b; }
  .badge-yellow { background: #fef3c7; color: #92400e; }
  .badge-gray { background: #f3f4f6; color: #374151; }

  /* ── Section divider ── */
  .section-note { background: #f0fdfe; border-left: 3px solid #087f83; padding: 8px 12px; margin: 12px 0; font-size: 9px; color: #555; }

  /* ── Footer ── */
  .footer { position: fixed; bottom: 20px; left: 50px; right: 50px; font-size: 8px; color: #999; border-top: 1px solid #e5e7eb; padding-top: 6px; }
</style>
</head>
<body>

{{-- ═══════════════════════════════════════════════════════════ --}}
{{-- COVER PAGE --}}
{{-- ═══════════════════════════════════════════════════════════ --}}
<div class="cover">
  <div class="org">{{ $tenant->name ?? 'Organisation' }}</div>
  <div class="subtitle">Board Governance Summary</div>
  <h1>Governance Report</h1>
  <div class="subtitle">{{ $period }}</div>

  <table>
    <tr><td>Report Type</td><td>Board Governance Analytics</td></tr>
    <tr><td>Organisation</td><td>{{ $tenant->name ?? '—' }}</td></tr>
    <tr><td>Reporting Period</td><td>{{ $period }}</td></tr>
    <tr><td>Total Meetings</td><td>{{ $meetingStats['total'] }}</td></tr>
    <tr><td>Generated On</td><td>{{ now()->format('d M Y, g:i A') }}</td></tr>
  </table>

  <div class="generated">Generated by BMMS — Board Meeting Management System</div>
</div>

<div class="page-break"></div>

{{-- ═══════════════════════════════════════════════════════════ --}}
{{-- SECTION 1: MEETING OVERVIEW --}}
{{-- ═══════════════════════════════════════════════════════════ --}}
<div class="page">
  <div class="footer">{{ $tenant->name ?? '' }} · Governance Report · Generated {{ now()->format('d M Y') }}</div>

  <h2>1. Meeting Overview</h2>

  <div class="stat-row">
    <div class="stat-cell">
      <div class="stat-number">{{ $meetingStats['total'] }}</div>
      <div class="stat-label">Total Meetings</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $meetingStats['this_year'] }}</div>
      <div class="stat-label">This Year</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $meetingStats['closed'] }}</div>
      <div class="stat-label">Completed</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $meetingStats['in_progress'] }}</div>
      <div class="stat-label">In Progress</div>
    </div>
  </div>

  @if(count($meetingStats['by_type']) > 0)
  <h3>Meetings by Type</h3>
  <table class="data">
    <tr>
      <th>Type</th>
      <th style="text-align:right">Count</th>
    </tr>
    @foreach($meetingStats['by_type'] as $type => $count)
    <tr>
      <td>{{ strtoupper($type) }}</td>
      <td style="text-align:right">{{ $count }}</td>
    </tr>
    @endforeach
  </table>
  @endif

  @if(count($meetings) > 0)
  <h3>Meeting Register</h3>
  <table class="data">
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Date</th>
      <th>Status</th>
      <th style="text-align:right">Invited</th>
      <th style="text-align:right">Present</th>
      <th style="text-align:right">Att %</th>
    </tr>
    @foreach($meetings as $m)
    @php
      $inv = $m->attendees->count();
      $prs = $m->attendees->where('attendance_status','present')->count();
      $att = $inv > 0 ? round($prs/$inv*100,0) : 0;
      $statusClass = match($m->status) {
        'closed','archived' => 'badge-green',
        'in_progress'       => 'badge-yellow',
        'cancelled'         => 'badge-red',
        default             => 'badge-gray',
      };
    @endphp
    <tr>
      <td>{{ Str::limit($m->title, 35) }}</td>
      <td>{{ strtoupper($m->type) }}</td>
      <td>{{ $m->scheduled_date?->format('d M Y') ?? '—' }}</td>
      <td><span class="badge {{ $statusClass }}">{{ ucfirst(str_replace('_',' ',$m->status)) }}</span></td>
      <td style="text-align:right">{{ $inv }}</td>
      <td style="text-align:right">{{ $prs }}</td>
      <td style="text-align:right">{{ $att }}%</td>
    </tr>
    @endforeach
  </table>
  @endif

</div>

<div class="page-break"></div>

{{-- ═══════════════════════════════════════════════════════════ --}}
{{-- SECTION 2: ATTENDANCE ANALYSIS --}}
{{-- ═══════════════════════════════════════════════════════════ --}}
<div class="page">
  <div class="footer">{{ $tenant->name ?? '' }} · Governance Report · Generated {{ now()->format('d M Y') }}</div>

  <h2>2. Attendance Analysis</h2>

  <div class="stat-row">
    <div class="stat-cell">
      <div class="stat-number">{{ $attendanceStats['total_invited'] }}</div>
      <div class="stat-label">Total Invitations</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $attendanceStats['total_attended'] }}</div>
      <div class="stat-label">Total Attendances</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $attendanceStats['attendance_rate'] }}%</div>
      <div class="stat-label">Avg Attendance Rate</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $attendanceStats['rsvp_response_rate'] }}%</div>
      <div class="stat-label">RSVP Response Rate</div>
    </div>
  </div>

  <div class="section-note">
    Attendance rate measures the proportion of invited members who were marked present. RSVP response rate measures the proportion who responded to the RSVP invitation (yes, no, maybe, or excused).
  </div>

</div>

<div class="page-break"></div>

{{-- ═══════════════════════════════════════════════════════════ --}}
{{-- SECTION 3: RESOLUTIONS & DECISIONS --}}
{{-- ═══════════════════════════════════════════════════════════ --}}
<div class="page">
  <div class="footer">{{ $tenant->name ?? '' }} · Governance Report · Generated {{ now()->format('d M Y') }}</div>

  <h2>3. Resolutions &amp; Decisions</h2>

  <div class="stat-row">
    <div class="stat-cell">
      <div class="stat-number">{{ $resolutionStats['total'] }}</div>
      <div class="stat-label">Total Resolutions</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $resolutionStats['passed'] }}</div>
      <div class="stat-label">Passed</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $resolutionStats['failed'] }}</div>
      <div class="stat-label">Failed</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $resolutionStats['pass_rate'] }}%</div>
      <div class="stat-label">Pass Rate</div>
    </div>
  </div>

  @if(count($resolutions) > 0)
  <h3>Resolution Register</h3>
  <table class="data">
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Meeting</th>
      <th>Type</th>
      <th>Status</th>
      <th style="text-align:right">Yes</th>
      <th style="text-align:right">No</th>
      <th style="text-align:right">Abs</th>
    </tr>
    @foreach($resolutions as $res)
    @php
      $statusClass = match($res->status) {
        'passed'   => 'badge-green',
        'failed'   => 'badge-red',
        'proposed' => 'badge-gray',
        'voting'   => 'badge-yellow',
        default    => 'badge-gray',
      };
    @endphp
    <tr>
      <td>{{ $loop->iteration }}</td>
      <td>{{ Str::limit($res->title, 30) }}</td>
      <td>{{ Str::limit($res->meeting?->title ?? '—', 20) }}</td>
      <td>{{ ucfirst(str_replace('_',' ',$res->type)) }}</td>
      <td><span class="badge {{ $statusClass }}">{{ ucfirst($res->status) }}</span></td>
      <td style="text-align:right">{{ $res->votes_yes }}</td>
      <td style="text-align:right">{{ $res->votes_no }}</td>
      <td style="text-align:right">{{ $res->votes_abstain }}</td>
    </tr>
    @endforeach
  </table>
  @endif

</div>

<div class="page-break"></div>

{{-- ═══════════════════════════════════════════════════════════ --}}
{{-- SECTION 4: ACTION ITEMS --}}
{{-- ═══════════════════════════════════════════════════════════ --}}
<div class="page">
  <div class="footer">{{ $tenant->name ?? '' }} · Governance Report · Generated {{ now()->format('d M Y') }}</div>

  <h2>4. Action Items</h2>

  <div class="stat-row">
    <div class="stat-cell">
      <div class="stat-number">{{ $actionStats['total'] }}</div>
      <div class="stat-label">Total</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $actionStats['open'] }}</div>
      <div class="stat-label">Open</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number">{{ $actionStats['done'] }}</div>
      <div class="stat-label">Done</div>
    </div>
    <div class="stat-cell">
      <div class="stat-number" style="color:{{ $actionStats['overdue'] > 0 ? '#dc2626' : '#087f83' }}">{{ $actionStats['overdue'] }}</div>
      <div class="stat-label">Overdue</div>
    </div>
  </div>

  @if(count($actionItems) > 0)
  <table class="data">
    <tr>
      <th>Title</th>
      <th>Meeting</th>
      <th>Assigned To</th>
      <th>Due</th>
      <th>Priority</th>
      <th>Status</th>
    </tr>
    @foreach($actionItems as $item)
    @php
      $isOverdue = $item->isOverdue();
      $statusClass = match(true) {
        $isOverdue              => 'badge-red',
        $item->status === 'done' => 'badge-green',
        $item->status === 'in_progress' => 'badge-yellow',
        default                 => 'badge-gray',
      };
    @endphp
    <tr>
      <td>{{ Str::limit($item->title, 30) }}</td>
      <td>{{ Str::limit($item->meeting?->title ?? '—', 20) }}</td>
      <td>{{ $item->assignedTo?->name ?? '—' }}</td>
      <td>{{ $item->due_date?->format('d M Y') ?? '—' }}</td>
      <td>{{ ucfirst($item->priority) }}</td>
      <td><span class="badge {{ $statusClass }}">{{ ucfirst($isOverdue ? 'Overdue' : str_replace('_',' ',$item->status)) }}</span></td>
    </tr>
    @endforeach
  </table>
  @endif

</div>

</body>
</html>
