<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: DejaVu Sans, Arial, sans-serif; font-size:11pt; color:#17202a; }

  .cover { page-break-after:always; }
  .cover-header { background:#1f6feb; color:#fff; padding:48px 56px 36px; }
  .cover-header .org { font-size:12pt; opacity:.85; margin-bottom:10px; }
  .cover-header .title { font-size:24pt; font-weight:bold; line-height:1.2; margin-bottom:6px; }
  .cover-header .sub { font-size:13pt; opacity:.9; }
  .cover-body { padding:36px 56px; }
  .meta { border-left:4px solid #1f6feb; padding-left:16px; margin-bottom:28px; }
  .meta table { width:100%; border-collapse:collapse; }
  .meta td { padding:5px 0; font-size:11pt; }
  .meta td:first-child { color:#647184; width:140px; }
  .meta td:last-child { font-weight:600; }
  .cover-footer { background:#f4f6f8; border-top:2px solid #1f6feb; padding:14px 56px; font-size:9pt; color:#647184; }

  /* Page header */
  .page { page-break-before:always; padding:36px 48px; }
  .page-header { border-bottom:1px solid #d8e0e8; padding-bottom:8px; margin-bottom:22px; font-size:9pt; color:#aaa; display:flex; justify-content:space-between; }
  h2 { font-size:14pt; color:#1f6feb; border-bottom:2px solid #1f6feb; padding-bottom:6px; margin-bottom:18px; }

  /* Agenda items */
  .item-block { margin-bottom:28px; }
  .item-num { font-size:10pt; font-weight:bold; color:#1f6feb; margin-bottom:4px; }
  .item-title { font-size:12pt; font-weight:bold; margin-bottom:8px; }
  .item-content { font-size:10.5pt; color:#333; line-height:1.65; white-space:pre-wrap; }
  .item-empty { font-size:10pt; color:#aaa; font-style:italic; }

  /* Resolutions */
  .resolution-block { margin-bottom:16px; padding:12px 16px; border-left:4px solid #238636; background:#f8fff9; }
  .resolution-block.failed { border-color:#e74c3c; background:#fff8f8; }
  .res-title { font-weight:bold; font-size:11pt; }
  .res-meta { font-size:9.5pt; color:#647184; margin-top:4px; }
  .res-result { font-size:9.5pt; font-weight:bold; margin-top:6px; }
  .res-result.passed { color:#238636; }
  .res-result.failed { color:#e74c3c; }

  /* Attendees */
  table.att { width:100%; border-collapse:collapse; font-size:10pt; }
  table.att th { background:#eef3f7; padding:7px 10px; text-align:left; font-size:9.5pt; color:#647184; border-bottom:1px solid #d8e0e8; }
  table.att td { padding:7px 10px; border-bottom:1px solid #f0f0f0; }

  /* Signatures */
  .sig-block { margin-top:60px; display:flex; gap:80px; }
  .sig-line { border-top:1px solid #333; width:200px; padding-top:6px; font-size:9.5pt; color:#647184; }
</style>
</head>
<body>

{{-- COVER --}}
<div class="cover">
  <div class="cover-header">
    <div class="org">{{ $meeting->tenant->name ?? 'BMMS' }}</div>
    <div class="title">Minutes of Meeting</div>
    <div class="sub">{{ $meeting->title }}</div>
  </div>
  <div class="cover-body">
    <div class="meta">
      <table>
        <tr><td>Meeting Type</td><td>{{ strtoupper($meeting->type) }}</td></tr>
        <tr><td>Date</td><td>{{ $meeting->scheduled_date?->format('l, d F Y') ?? 'TBC' }}</td></tr>
        <tr><td>Time</td><td>
          @if($meeting->start_time)
            {{ \Carbon\Carbon::parse($meeting->start_time)->format('g:i A') }}
            @if($meeting->end_time) – {{ \Carbon\Carbon::parse($meeting->end_time)->format('g:i A') }} @endif
          @else TBC @endif
        </td></tr>
        <tr><td>Location</td><td>{{ $meeting->location ?: 'TBC' }}</td></tr>
        <tr><td>Chairperson</td><td>{{ $meeting->chairperson?->name ?: '—' }}</td></tr>
        <tr><td>Secretary</td><td>{{ $meeting->secretary?->name ?: '—' }}</td></tr>
        <tr><td>Drafted By</td><td>{{ $minutes->draftedBy?->name ?: '—' }}</td></tr>
        <tr><td>Approved By</td><td>{{ $minutes->approvedBy?->name ?: '—' }}</td></tr>
        <tr><td>Approved On</td><td>{{ $minutes->approved_at?->format('d M Y') ?: '—' }}</td></tr>
      </table>
    </div>
    <p style="font-size:9.5pt; color:#647184;">
      These minutes are a true and accurate record of the meeting proceedings as approved by the board.
    </p>
  </div>
  <div class="cover-footer">Generated by BMMS — {{ now()->format('d M Y') }}</div>
</div>

{{-- ATTENDEES --}}
<div class="page">
  <div class="page-header">
    <span>{{ $meeting->title }} — Minutes</span>
    <span>{{ $meeting->scheduled_date?->format('d M Y') }}</span>
  </div>
  <h2>Attendance</h2>
  @if($meeting->attendees->count())
    <table class="att">
      <thead><tr><th>Name</th><th>Role</th><th>RSVP</th><th>Attended</th></tr></thead>
      <tbody>
        @foreach($meeting->attendees as $att)
          <tr>
            <td>{{ $att->user?->name }}</td>
            <td style="color:#647184; font-size:9.5pt">{{ ucfirst(str_replace('_',' ',$att->role ?? '')) }}</td>
            <td style="text-transform:uppercase; font-size:9pt; color:{{ $att->rsvp_status === 'yes' ? '#238636' : '#647184' }}">
              {{ $att->rsvp_status ?? '—' }}
            </td>
            <td>
              @php $attended = $att->attendance_status ?? null; @endphp
              <span style="color:{{ $attended === 'present' ? '#238636' : ($attended === 'absent' ? '#e74c3c' : '#647184') }}">
                {{ ucfirst($attended ?? '—') }}
              </span>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
  @else
    <p style="color:#aaa; font-style:italic">No attendance records.</p>
  @endif
</div>

{{-- MINUTES PER AGENDA ITEM --}}
<div class="page">
  <div class="page-header">
    <span>{{ $meeting->title }} — Minutes</span>
    <span>{{ $meeting->scheduled_date?->format('d M Y') }}</span>
  </div>
  <h2>Minutes</h2>

  @php $content = $minutes->content ?? []; @endphp

  @forelse($content as $item)
    <div class="item-block">
      @if(!empty($item['title']))
        <div class="item-num">{{ $item['title'] }}</div>
      @endif
      @if(!empty($item['content']))
        <div class="item-content">{{ $item['content'] }}</div>
      @else
        <div class="item-empty">No minutes recorded for this item.</div>
      @endif
    </div>
  @empty
    <p style="color:#aaa; font-style:italic">No minutes content recorded.</p>
  @endforelse
</div>

{{-- RESOLUTIONS --}}
@if($meeting->resolutions->count())
<div class="page">
  <div class="page-header">
    <span>{{ $meeting->title }} — Minutes</span>
    <span>{{ $meeting->scheduled_date?->format('d M Y') }}</span>
  </div>
  <h2>Resolutions</h2>

  @foreach($meeting->resolutions as $res)
    <div class="resolution-block {{ $res->status === 'failed' ? 'failed' : '' }}">
      <div class="res-title">{{ $res->title }}</div>
      @if($res->body)
        <div style="font-size:10pt; color:#333; margin-top:6px; font-style:italic;">{{ $res->body }}</div>
      @endif
      <div class="res-meta">
        {{ \App\Models\Resolution::MAJORITY_LABELS[$res->required_majority] ?? '' }}
        &nbsp;|&nbsp; Proposed by {{ $res->proposedBy?->name ?? '—' }}
        @if($res->secondedBy) &nbsp;|&nbsp; Seconded by {{ $res->secondedBy?->name }} @endif
      </div>
      @if($res->isDecided())
        <div class="res-result {{ $res->status }}">
          {{ strtoupper($res->status) }}
          — For: {{ $res->votes_yes }}, Against: {{ $res->votes_no }}, Abstain: {{ $res->votes_abstain }}
        </div>
      @endif
    </div>
  @endforeach
</div>
@endif

{{-- SIGNATURE BLOCK --}}
<div class="page">
  <div class="page-header">
    <span>{{ $meeting->title }} — Minutes</span>
    <span>{{ $meeting->scheduled_date?->format('d M Y') }}</span>
  </div>
  <h2>Confirmation</h2>
  <p style="font-size:10.5pt; margin-bottom:40px;">
    We, the undersigned, confirm that these minutes are a true and accurate record of the
    {{ $meeting->title }} held on {{ $meeting->scheduled_date?->format('d F Y') }}.
  </p>
  <div class="sig-block">
    <div>
      <div class="sig-line">Chairperson: {{ $meeting->chairperson?->name }}</div>
      <div style="margin-top:8px; font-size:9pt; color:#aaa;">Date: _______________</div>
    </div>
    <div>
      <div class="sig-line">Secretary: {{ $meeting->secretary?->name }}</div>
      <div style="margin-top:8px; font-size:9pt; color:#aaa;">Date: _______________</div>
    </div>
  </div>
</div>

</body>
</html>
