<?php

namespace App\Filament\Tenant\Resources\MeetingResource\RelationManagers;

use App\Models\BoardPack;
use App\Services\BoardPackService;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables;
use Filament\Tables\Table;

class BoardPacksRelationManager extends RelationManager
{
    protected static string $relationship = 'boardPacks';
    protected static ?string $title = 'Board Packs';

    public function form(Schema $schema): Schema
    {
        return $schema->components([]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('version')
            ->defaultSort('version', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('version')
                    ->label('Version')
                    ->formatStateUsing(fn (int $state): string => "v{$state}")
                    ->badge()
                    ->color('info'),

                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'published' => 'success',
                        default     => 'warning',
                    }),

                Tables\Columns\TextColumn::make('items_count')
                    ->label('Documents')
                    ->getStateUsing(fn (BoardPack $record): int => $record->items()->count()),

                Tables\Columns\TextColumn::make('generatedBy.name')
                    ->label('Generated By'),

                Tables\Columns\TextColumn::make('generated_at')
                    ->label('Generated')
                    ->dateTime('d M Y, g:i A'),

                Tables\Columns\TextColumn::make('published_at')
                    ->label('Published')
                    ->dateTime('d M Y, g:i A')
                    ->placeholder('—'),
            ])
            ->headerActions([
                Actions\Action::make('generate')
                    ->label('Generate New Board Pack')
                    ->icon(Heroicon::OutlinedDocumentPlus)
                    ->color('primary')
                    ->requiresConfirmation()
                    ->modalHeading('Generate Board Pack')
                    ->modalDescription('This will compile all published documents for this meeting into a new board pack (Cover PDF + Document Index). Only documents in "Published" stage will be included.')
                    ->modalSubmitActionLabel('Generate')
                    ->action(function (): void {
                        $meeting = $this->getOwnerRecord();
                        $service = app(BoardPackService::class);

                        try {
                            $service->generate($meeting, auth()->id());

                            Notification::make()
                                ->title('Board pack generated successfully')
                                ->success()
                                ->send();
                        } catch (\Throwable $e) {
                            Notification::make()
                                ->title('Generation failed')
                                ->body($e->getMessage())
                                ->danger()
                                ->send();
                        }
                    }),
            ])
            ->actions([
                Actions\Action::make('publish')
                    ->label('Publish')
                    ->icon(Heroicon::OutlinedCheckCircle)
                    ->color('success')
                    ->requiresConfirmation()
                    ->modalDescription('Publishing this board pack will make it visible to attendees and will advance the meeting status to "Board Pack Generated".')
                    ->visible(fn (BoardPack $record): bool => $record->status === 'draft')
                    ->action(function (BoardPack $record): void {
                        app(BoardPackService::class)->publish($record);

                        Notification::make()
                            ->title('Board pack published')
                            ->success()
                            ->send();
                    }),

                Actions\Action::make('download_pdf')
                    ->label('Cover PDF')
                    ->icon(Heroicon::OutlinedArrowDownTray)
                    ->color('gray')
                    ->url(fn (BoardPack $record): string => route('board-packs.download-pdf', $record->id))
                    ->openUrlInNewTab()
                    ->visible(fn (BoardPack $record): bool => (bool) $record->file_path),

                Actions\Action::make('download_zip')
                    ->label('Full Package (ZIP)')
                    ->icon(Heroicon::OutlinedArchiveBoxArrowDown)
                    ->color('gray')
                    ->url(fn (BoardPack $record): string => route('board-packs.download-zip', $record->id))
                    ->openUrlInNewTab(),

                Actions\DeleteAction::make()
                    ->visible(fn (BoardPack $record): bool => $record->status === 'draft'),
            ])
            ->bulkActions([]);
    }
}
